In [ ]:
import zipfile
import os

In [ ]:
zip_path = "/content/archive (4).zip"
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
  zip_ref.extractall("/content/parkinson_data")

Above codes will import packages related to file management in os and will extract the data zip file

In [ ]:
import pandas as pd

df = pd.read_csv("/content/parkinson_data/parkinsons_disease_dataset.csv")
df.head()

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score,Parkinsons_Status
0,78,Male,5.19,287.62,3.82,2.98,8.05,9.11,6.67,79.13,0.97,7.39,No,11.41,1
1,68,Female,6.22,281.92,3.38,3.79,1.04,7.64,1.43,97.50,1.67,1.71,Yes,12.58,0
2,54,Female,4.20,231.59,2.89,4.03,8.14,2.05,3.80,73.40,6.30,9.79,Yes,1.55,0
3,82,Male,8.77,236.50,3.16,2.89,5.35,6.52,4.87,87.81,3.41,2.33,No,92.83,1
4,47,Male,5.23,100.48,4.60,3.43,6.80,8.13,3.59,94.33,6.41,0.52,Yes,36.37,0

Now i'll preprocess the data set

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23000 entries, 0 to 22999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   23000 non-null  int64
 1   Sex                   23000 non-null  object
 2   Tremor_Intensity      23000 non-null  float64
 3   Voice_Pitch           23000 non-null  float64
 4   Voice_Jitter          23000 non-null  float64
 5   Voice_Shimmer         23000 non-null  float64
 6   Bradykinesia_Score    23000 non-null  float64
 7   Postural_Instability  23000 non-null  float64
 8   Rigidity_Level        23000 non-null  float64
 9   UPDRS_Score           23000 non-null  float64
 10  Handwriting_Change    23000 non-null  float64
 11  Walking_Difficulty    23000 non-null  float64
 12  Family_History        23000 non-null  object
 13  MRI_Score             23000 non-null  float64
 14  Parkinsons_Status     23000 non-null  int64
dtypes: float64(11), int64(2), object(2)
memory usage: 2.6+ MB

In [ ]:
df.isnull().sum()

Age                     0
Sex                     0
Tremor_Intensity        0
Voice_Pitch             0
Voice_Jitter            0
Voice_Shimmer           0
Bradykinesia_Score      0
Postural_Instability    0
Rigidity_Level          0
UPDRS_Score             0
Handwriting_Change      0
Walking_Difficulty      0
Family_History          0
MRI_Score               0
Parkinsons_Status       0
dtype: int64

In [ ]:
df['Sex'] = df['Sex'].map({"Male": 0, "Female": 1})
df['Family_History'] = df['Family_History'].map({"No": 0, "Yes": 1})

In [ ]:
df.head()

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score,Parkinsons_Status
0,78,0,5.19,287.62,3.82,2.98,8.05,9.11,6.67,79.13,0.97,7.39,0,11.41,1
1,68,1,6.22,281.92,3.38,3.79,1.04,7.64,1.43,97.50,1.67,1.71,1,12.58,0
2,54,1,4.20,231.59,2.89,4.03,8.14,2.05,3.80,73.40,6.30,9.79,1,1.55,0
3,82,0,8.77,236.50,3.16,2.89,5.35,6.52,4.87,87.81,3.41,2.33,0,92.83,1
4,47,0,5.23,100.48,4.60,3.43,6.80,8.13,3.59,94.33,6.41,0.52,1,36.37,0

In [ ]:
df['Parkinsons_Status'].value_counts()

Parkinsons_Status
0    13807
1     9193
Name: count, dtype: int64

In [ ]:
X = df.drop(['Parkinsons_Status'], axis=1)
y = df['Parkinsons_Status']

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=82, stratify=y)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report

models = {
    "Logistic Regression": LogisticRegression(max_iter=100, class_weight='balanced'),
    "Random Forest": RandomForestClassifier(class_weight='balanced'),
    "SVM": SVC(class_weight='balanced')
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    print(f"\nModel: {name}")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Model: Logistic Regression
Accuracy: 0.5128985507246376
Classification Report:
               precision    recall  f1-score   support

           0       0.61      0.51      0.56      4142
           1       0.41      0.51      0.46      2758

    accuracy                           0.51      6900
   macro avg       0.51      0.51      0.51      6900
weighted avg       0.53      0.51      0.52      6900


Model: Random Forest
Accuracy: 0.5888405797101449
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.95      0.73      4142
           1       0.39      0.05      0.09      2758

    accuracy                           0.59      6900
   macro avg       0.49      0.50      0.41      6900
weighted avg       0.52      0.59      0.48      6900


Model: SVM
Accuracy: 0.5031884057971014
Classification Report:
               precision    recall  f1-score   support

           0       0.60      0.51      0.55      4142
           1       0.40      0.49      0.44      2758

    accuracy                           0.50      6900
   macro avg       0.50      0.50      0.50      6900
weighted avg       0.52      0.50      0.51      6900