In [1]:
import pandas as pd

#import kagglehub

# Download latest version
#path = kagglehub.dataset_download("miadul/parkinsons-disease-synthetic-dataset")

parkinsonsData = pd.read_csv("parkinsons_disease_dataset.csv")
parkinsonsData.head()

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score,Parkinsons_Status
0,78,Male,5.19,287.62,3.82,2.98,8.05,9.11,6.67,79.13,0.97,7.39,No,11.41,1
1,68,Female,6.22,281.92,3.38,3.79,1.04,7.64,1.43,97.50,1.67,1.71,Yes,12.58,0
2,54,Female,4.20,231.59,2.89,4.03,8.14,2.05,3.80,73.40,6.30,9.79,Yes,1.55,0
3,82,Male,8.77,236.50,3.16,2.89,5.35,6.52,4.87,87.81,3.41,2.33,No,92.83,1
4,47,Male,5.23,100.48,4.60,3.43,6.80,8.13,3.59,94.33,6.41,0.52,Yes,36.37,0

In [2]:
parkinsonsData.columns

Index(['Age', 'Sex', 'Tremor_Intensity', 'Voice_Pitch', 'Voice_Jitter',
       'Voice_Shimmer', 'Bradykinesia_Score', 'Postural_Instability',
       'Rigidity_Level', 'UPDRS_Score', 'Handwriting_Change',
       'Walking_Difficulty', 'Family_History', 'MRI_Score',
       'Parkinsons_Status'],
      dtype='object')

In [3]:
y = parkinsonsData.Parkinsons_Status

In [4]:
parkinsonsData['Sex'] = parkinsonsData['Sex'].map({"Male":0,"Female":1})
parkinsonsData['Family_History'] = parkinsonsData['Family_History'].map({"No":0,"Yes":1})

In [5]:
features = ['Age','Sex','Tremor_Intensity','Voice_Pitch','Voice_Jitter','Voice_Shimmer','Bradykinesia_Score','Postural_Instability','Rigidity_Level','UPDRS_Score','Handwriting_Change','Walking_Difficulty','Family_History','MRI_Score']
X = parkinsonsData[features]

In [6]:
X.describe()

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score
count,23000.000000,23000.000000,23000.000000,23000.000000,23000.00000,23000.000000,23000.000000,23000.000000,23000.000000,23000.000000,23000.000000,23000.000000,23000.000000,23000.000000
mean,62.352783,0.495348,4.965473,200.423182,2.54379,2.551544,4.999794,5.032178,5.009445,49.758583,5.039512,4.986073,0.501739,50.063531
std,13.192461,0.499989,2.885786,57.487770,1.41737,1.416150,2.883474,2.891638,2.877759,28.936998,2.891534,2.887473,0.500008,28.885844
min,40.000000,0.000000,0.000000,100.000000,0.10000,0.100000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,51.000000,0.000000,2.450000,151.207500,1.30000,1.320000,2.500000,2.520000,2.547500,24.280000,2.530000,2.490000,0.000000,25.027500
50%,62.000000,0.000000,4.950000,200.600000,2.56000,2.560000,5.000000,5.035000,5.010000,49.770000,5.040000,4.970000,1.000000,50.300000
75%,74.000000,1.000000,7.470000,250.465000,3.78000,3.780000,7.490000,7.540000,7.480000,74.832500,7.530000,7.470000,1.000000,75.242500
max,85.000000,1.000000,10.000000,299.990000,5.00000,5.000000,10.000000,10.000000,10.000000,100.000000,10.000000,10.000000,1.000000,99.990000

In [7]:
X.head()

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score
0,78,0,5.19,287.62,3.82,2.98,8.05,9.11,6.67,79.13,0.97,7.39,0,11.41
1,68,1,6.22,281.92,3.38,3.79,1.04,7.64,1.43,97.50,1.67,1.71,1,12.58
2,54,1,4.20,231.59,2.89,4.03,8.14,2.05,3.80,73.40,6.30,9.79,1,1.55
3,82,0,8.77,236.50,3.16,2.89,5.35,6.52,4.87,87.81,3.41,2.33,0,92.83
4,47,0,5.23,100.48,4.60,3.43,6.80,8.13,3.59,94.33,6.41,0.52,1,36.37

In [8]:
from sklearn.tree import DecisionTreeRegressor
# Define model. Specify a number for random_state to ensure same results each run
parkinson_detection_model = DecisionTreeRegressor(random_state=1)

#Fit model
parkinson_detection_model.fit(X,y)

DecisionTreeRegressor(random_state=1)

In [9]:
print("Making predictions for the following 5 ppl : ")
print(X)
print("The predictions are")
print(parkinson_detection_model.predict(X))

Making predictions for the following 5 ppl :
       Age  Sex  Tremor_Intensity  Voice_Pitch  Voice_Jitter  Voice_Shimmer  \
0       78    0              5.19       287.62          3.82           2.98
1       68    1              6.22       281.92          3.38           3.79
2       54    1              4.20       231.59          2.89           4.03
3       82    0              8.77       236.50          3.16           2.89
4       47    0              5.23       100.48          4.60           3.43
...    ...  ...               ...          ...           ...            ...
22995   81    1              4.10       102.12          0.72           3.93
22996   65    0              0.25       290.78          0.12           2.29
22997   81    1              4.19       254.47          4.97           3.70
22998   80    0              6.60       239.11          2.31           1.60
22999   41    1              8.91       105.96          0.44           0.59

       Bradykinesia_Score  Postural_Instability  Rigidity_Level  UPDRS_Score  \
0                    8.05                  9.11            6.67        79.13
1                    1.04                  7.64            1.43        97.50
2                    8.14                  2.05            3.80        73.40
3                    5.35                  6.52            4.87        87.81
4                    6.80                  8.13            3.59        94.33
...                   ...                   ...             ...          ...
22995                7.18                  9.45            9.81        46.06
22996                0.32                  2.43            6.39         8.81
22997                4.79                  0.79            6.68        23.80
22998                4.90                  8.03            6.94        35.20
22999                0.43                  2.30            9.77        72.33

       Handwriting_Change  Walking_Difficulty  Family_History  MRI_Score
0                    0.97                7.39               0      11.41
1                    1.67                1.71               1      12.58
2                    6.30                9.79               1       1.55
3                    3.41                2.33               0      92.83
4                    6.41                0.52               1      36.37
...                   ...                 ...             ...        ...
22995                5.65                9.90               1      36.29
22996                3.94                5.09               0      16.44
22997                9.71                4.38               0      53.74
22998                9.72                9.04               0      82.09
22999                9.25                5.59               0      70.50

[23000 rows x 14 columns]
The predictions are
[1. 0. 0. ... 0. 1. 1.]

In [10]:
parkinsonsData

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score,Parkinsons_Status
0,78,0,5.19,287.62,3.82,2.98,8.05,9.11,6.67,79.13,0.97,7.39,0,11.41,1
1,68,1,6.22,281.92,3.38,3.79,1.04,7.64,1.43,97.50,1.67,1.71,1,12.58,0
2,54,1,4.20,231.59,2.89,4.03,8.14,2.05,3.80,73.40,6.30,9.79,1,1.55,0
3,82,0,8.77,236.50,3.16,2.89,5.35,6.52,4.87,87.81,3.41,2.33,0,92.83,1
4,47,0,5.23,100.48,4.60,3.43,6.80,8.13,3.59,94.33,6.41,0.52,1,36.37,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22995,81,1,4.10,102.12,0.72,3.93,7.18,9.45,9.81,46.06,5.65,9.90,1,36.29,0
22996,65,0,0.25,290.78,0.12,2.29,0.32,2.43,6.39,8.81,3.94,5.09,0,16.44,0
22997,81,1,4.19,254.47,4.97,3.70,4.79,0.79,6.68,23.80,9.71,4.38,0,53.74,0
22998,80,0,6.60,239.11,2.31,1.60,4.90,8.03,6.94,35.20,9.72,9.04,0,82.09,1
22999,41,1,8.91,105.96,0.44,0.59,0.43,2.30,9.77,72.33,9.25,5.59,0,70.50,1

In [11]:
# Import the train_test_split function
from sklearn.model_selection import train_test_split

train_X, val_X, train_y, val_y = train_test_split(X ,y ,random_state = 1)

In [12]:
parkinson_detection_model = DecisionTreeRegressor(random_state = 1)

# Fit parkinson_detection_model with the training data.

parkinson_detection_model.fit(train_X,train_y)

DecisionTreeRegressor(random_state=1)

In [13]:
# Predict with all validation observations
val_predictions = parkinson_detection_model.predict(val_X)

In [14]:
# print the top few validation predictions
print(val_predictions)
# print the top few actual results from validation data
print(val_y)

[1. 0. 1. ... 0. 1. 1.]
10673    1
13215    0
13736    1
21205    1
7473     0
        ..
15565    0
6612     0
18946    0
2257     0
8505     1
Name: Parkinsons_Status, Length: 5750, dtype: int64

In [15]:
from sklearn.metrics import mean_absolute_error
val_mae = mean_absolute_error(val_y,val_predictions)


print(val_mae)

0.4831304347826087

In [16]:
def get_mae(max_leaf_nodes,train_X,val_X,train_y,val_y):
    model = DecisionTreeRegressor(max_leaf_nodes = max_leaf_nodes, random_state= 0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    mae = mean_absolute_error(val_y, preds_val)
    return(mae)

In [17]:
candidate_max_leaf_nodes = [5, 25, 50, 100, 250, 500]
meas = []
#find the ideal tree size from candidate_max_leaf_nodes
for max_leaf_nodes in candidate_max_leaf_nodes:
    my_mea = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    meas.append(my_mea)
    print("max leaf nodes: ",max_leaf_nodes,"  MAE: ", my_mea)
    if min(meas) == my_mea:
        best_tree_size = max_leaf_nodes

# Store the best value of max_leaf_nodes (it will be either 5, 25, 50, 100, 250 or 500)
#best_tree_size = min(meas)
print(best_tree_size)

max leaf nodes:  5   MAE:  0.47921766403406574
max leaf nodes:  25   MAE:  0.4796490127041695
max leaf nodes:  50   MAE:  0.48005695154201977
max leaf nodes:  100   MAE:  0.4801129690963549
max leaf nodes:  250   MAE:  0.47950538486036803
max leaf nodes:  500   MAE:  0.4797347893663066
5

In [18]:
candidate_max_leaf_nodes = [2, 3, 4, 5, 6,7]
meas = []
#find the ideal tree size from candidate_max_leaf_nodes
for max_leaf_nodes in candidate_max_leaf_nodes:
    my_mea = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    meas.append(my_mea)
    print("max leaf nodes: ",max_leaf_nodes,"  MAE: ", my_mea)
    if min(meas) == my_mea:
        best_tree_size = max_leaf_nodes

# Store the best value of max_leaf_nodes (it will be either  2, 3, 4, 5, 6 or 7)
#best_tree_size = min(meas)
print(best_tree_size)

max leaf nodes:  2   MAE:  0.4790396357734503
max leaf nodes:  3   MAE:  0.4791796646765601
max leaf nodes:  4   MAE:  0.47914714075743453
max leaf nodes:  5   MAE:  0.47921766403406574
max leaf nodes:  6   MAE:  0.47933933143548213
max leaf nodes:  7   MAE:  0.47926319821050345
2

In [19]:
# Fill in argument to make optimal size and uncomment
final_model = DecisionTreeRegressor(max_leaf_nodes=best_tree_size,random_state=1)

# fit the final model and uncomment the next two lines
final_model.fit(X,y)

DecisionTreeRegressor(max_leaf_nodes=2, random_state=1)

In [20]:
my_mea = get_mae(best_tree_size, train_X, val_X, train_y, val_y)
print(my_mea)

0.4790396357734503

In [21]:
from sklearn.ensemble import RandomForestRegressor

#Define the model. Set random_state to 1
rf_model = RandomForestRegressor(random_state=1)

#fit model
rf_model.fit(train_X,train_y)
rf_val_predictions = rf_model.predict(val_X)

# Calculate the mean absolute error of Random Forest model on the validation data
rf_val_mae = mean_absolute_error(rf_val_predictions, val_y)

print("Validation MAE for Random Forest Model: {:}".format(rf_val_mae))

Validation MAE for Random Forest Model: 0.4816017391304348

In [22]:
# To improve accuracy, creating a new Random Forest model which will train on all training data
rf_model_on_full_data = RandomForestRegressor(random_state=1)

# fit rf_model_on_full_data on all data from the training data
rf_model_on_full_data.fit(X,y)

RandomForestRegressor(random_state=1)

In [23]:
# The list of columns is stored in a variable called features
val_X = val_X[features]
# make predictions which we will submit.
test_preds = rf_model_on_full_data.predict(val_X)

In [24]:
# Calculate the mean absolute error of Random Forest model on the validation data
rf_val_mae = mean_absolute_error(test_preds, val_y)

print("Validation MAE for Random Forest Model: {:}".format(rf_val_mae))

Validation MAE for Random Forest Model: 0.1772417391304348

In [25]:
val_X.head()

,Age,Sex,Tremor_Intensity,Voice_Pitch,Voice_Jitter,Voice_Shimmer,Bradykinesia_Score,Postural_Instability,Rigidity_Level,UPDRS_Score,Handwriting_Change,Walking_Difficulty,Family_History,MRI_Score
10673,72,0,5.06,298.76,1.26,3.30,2.08,7.24,7.32,67.93,9.96,0.71,1,66.18
13215,66,0,6.91,147.83,0.46,3.09,1.71,2.19,0.87,82.41,3.17,5.32,0,57.46
13736,43,1,9.43,241.32,1.11,3.32,3.04,3.38,2.25,36.15,9.84,9.76,1,75.28
21205,56,1,3.46,115.44,2.00,0.79,1.52,4.17,1.99,92.53,3.11,6.47,0,27.00
7473,43,0,6.93,224.54,1.03,4.10,5.17,0.40,9.77,52.10,9.83,7.59,0,97.66

In [27]:
# Create an empty list to store the new, thresholded predictions
status_thresholded = []

# Loop through each prediction
for pred in test_preds:
    if pred >= 0.5:
        status_thresholded.append(1)
    else:
        status_thresholded.append(0)

# Create the output DataFrame with the thresholded predictions
output = pd.DataFrame({'Id': val_X.index,
                       'Status': status_thresholded})
output.to_csv('submission.csv', index=False)

In [28]:
output

         Id  Status
0     10673       1
1     13215       0
2     13736       1
3     21205       1
4      7473       0
...     ...     ...
5745  15565       0
5746   6612       0
5747  18946       0
5748   2257       0
5749   8505       1

[5750 rows x 2 columns]

In [29]:
inputData = pd.DataFrame({'Id': parkinsonsData.index,
                          'Status': parkinsonsData.Parkinsons_Status})
inputData.to_csv('inputData.csv',index=False)

In [30]:
inputData

          Id  Status
0          0       1
1          1       0
2          2       0
3          3       1
4          4       0
...      ...     ...
22995  22995       0
22996  22996       0
22997  22997       0
22998  22998       1
22999  22999       1

[23000 rows x 2 columns]